name: kc4align
channels:
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.7
  - numpy==1.19.2
  - cython==0.29.22
  - pip:
    - torch==1.5.1
    - fastBPE==0.1.0
    - transliterate==1.10.2
    - jieba==0.42.1
    - underthesea==1.3.1
    - deep-translator==1.4.4
    - hanziconv==0.2.1